# Generated by Django 2.2.2 on 2019-08-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='GUI.Scenario'),
        ),
    ]
