# Generated by Django 2.2.2 on 2019-09-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramreceivedmsg',
            name='proccessed',
            field=models.NullBooleanField(default=False),
        ),
    ]
