# Generated by Django 2.2.2 on 2019-08-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0004_scenario_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='social',
        ),
        migrations.AddField(
            model_name='trigger',
            name='social',
            field=models.CharField(choices=[('telegram', 'telegram'), ('vk', 'vk'), ('whatsapp', 'whatsapp'), ('facebook', 'facebook')], default='telegram', max_length=20),
        ),
    ]
