# Generated by Django 2.2.2 on 2019-08-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0005_auto_20190816_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='facebook_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='telegram_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='vk_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='whatsapp_status',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
