# Generated by Django 2.2.2 on 2019-08-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0007_auto_20190819_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoride',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='broadcastmessages',
            name='text',
        ),
        migrations.AddField(
            model_name='autoride',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GUI.Scenario'),
        ),
        migrations.AddField(
            model_name='broadcastmessages',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GUI.Scenario'),
        ),
        migrations.AddField(
            model_name='facebookusers',
            name='user_data',
            field=models.CharField(blank=True, default='main', max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='telegramusers',
            name='user_data',
            field=models.CharField(blank=True, default='main', max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='vkusers',
            name='user_data',
            field=models.CharField(blank=True, default='main', max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='whatsappusers',
            name='user_data',
            field=models.CharField(blank=True, default='main', max_length=4096, null=True),
        ),
    ]
