# Generated by Django 2.2.2 on 2019-08-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0008_auto_20190822_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='destination',
            field=models.CharField(choices=[('', ''), ('broadcast', 'broadcast'), ('autoride', 'autoride')], default='', max_length=20),
        ),
    ]
