# Generated by Django 2.2.2 on 2019-08-24 21:05

import GUI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0009_scenario_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='id',
            field=models.AutoField(auto_created=True, default=GUI.models.auto_increment_scenario, primary_key=True, serialize=False, unique=True),
        ),
    ]
