# Generated by Django 2.2.2 on 2019-08-25 22:50

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0010_auto_20190824_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='messages',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=[{'facebook': {'keyboard': [], 'text': ''}, 'telegram': {'keyboard': [], 'text': ''}, 'vk': {'keyboard': [], 'text': ''}, 'whatsapp': {'keyboard': [], 'text': ''}}], null=True),
        ),
    ]
