# Generated by Django 2.2.2 on 2019-08-26 07:36

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0011_auto_20190825_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='messages',
            field=django_extensions.db.fields.json.JSONField(blank=True, default={'facebook': [{'keyboard': [], 'text': ''}], 'telegram': [{'keyboard': [], 'text': ''}], 'vk': [{'keyboard': [], 'text': ''}], 'whatsapp': [{'keyboard': [], 'text': ''}]}, null=True),
        ),
    ]
