# Generated by Django 2.2.2 on 2019-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0012_auto_20190826_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='application_will_send',
            field=models.BooleanField(default=False),
        ),
    ]
