# Generated by Django 2.2.2 on 2019-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0013_manager_application_will_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manager',
            name='payed_end_date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
