# Generated by Django 2.2.2 on 2019-08-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUI', '0014_auto_20190828_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='keyboard',
            field=models.CharField(blank=True, default='{}', max_length=256, null=True),
        ),
    ]
